### ISSUE TITLE
Netlify CMS

### ISSUE THREAD

**Issue by rahxuls** [renyuanz/leonids#100]
If this comes with pre-installed netlify cms many new user will come. As this is very amazing template.

**Comment by renyuanz** [comment]
Thanks for the suggestion, I do really appreciate it. Personally never tried netlify cms, will need some help on this.

**Comment by rahxuls** [comment]
Yea I'm working on it. The reason if we've have pre-configured netlify cms is that many new developers who are blogger have to start there own blog but sometimes it is just a sort of a lot task to make file and write the date and all. Adding netlify cms will help everyone just writing in markdown and posting it. Just visiting site-admin/admin and logging in with netlify or GitHub credentials and writing your new post and posting it.

**Comment by renyuanz** [comment]
Added a one-click deploy to Netlify CMS button in README.md. Thanks for the suggestion, it was really easy to quickly setup
