### ISSUE TITLE
Anything we can do about the highlighter page build warning? _config.yml

### ISSUE THREAD

**Issue by SoumitraAgarwal** [renyuanz/leonids#16]
Github pages does not support `pygments`. This is the email I received 

>The page build completed successfully, but returned the following warning:
You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.
For information on troubleshooting Jekyll see:
  https://help.github.com/articles/troubleshooting-jekyll-builds
If you have any questions you can contact us by replying to this email.

Can we add `rouge` as the default highlighter and put `pygments` as an alternate comments

**Comment by renyuanz** [comment]
Yeah, that's a known "bug". I'll do it. Thanks :p

**Comment by renyuanz** [comment]
Done.

In fact, I fixed it in `gh-pages`'s config file but not in `master`'s one. It's weird. Thanks for reminding.

Closing it.
