### ISSUE TITLE
Missing .bundle file

### ISSUE THREAD

**Issue by Ridermansb** [renyuanz/leonids#2]
After fork/clone repo, update `_config.yml` and try to execute `bundle exec jekyll build` a error occur

    $ bundle exec jekyll build
    Could not locate Gemfile or .bundle/ directory

**in master brach**

**Comment by renyuanz** [comment]
You can try `jekyll server` instead.

**Comment by Ridermansb** [comment]
Works :+1: 
maybe you can remove `bundle exec jekyll build` from docs

**Comment by Shellcat-Zero** [comment]
"jekyll server" works, and "bundle exec jekyll build" is still failing.  Please do update the docs on this.
