### ISSUE TITLE
Home button in categories list

### ISSUE THREAD

**Issue by SoumitraAgarwal** [renyuanz/leonids#20]
Since we have one home button for every post, putting on in the categories list would add to the uniformity of the layout. I know that the portion of "your name" links to the home, but it is tougher to find and if we are doing it in posts we may as well do it in the categories, tags etc. There are 2 ways we can handle this 

1. By adding a button to each one of categories, tags, archives etc. :worried:
2. Add a home button to the sidebar and no such hassle is required.

Any suggestions?

**Comment by renyuanz** [comment]
I'll give it a try this weekend. 😀

**Comment by SoumitraAgarwal** [comment]
Sure. Tell me if I can contribute in any way :smile:

**Comment by SoumitraAgarwal** [comment]
Did you get time to work on this? :smile:

**Comment by renyuanz** [comment]
Finally I got the time to fix this. I added a home link in the sidebar navigation. See [commit 9cf4392](https://github.com/renyuanz/leonids/commit/9cf4392565869d3d44d9131761730e42912368ba)
