### ISSUE TITLE
leonids gem installs okay but can't build site

### ISSUE THREAD

**Issue by kmorgen1** [renyuanz/leonids#28]
I installed a new site following the official doc. Using bundle exec jekyll it builds without problems. Then I added leonids also following the official docs. When trying to buid jekyll throws the following errors:

```
    Liquid Warning: Liquid syntax error (line 7): Expected dotdot but found comparison in "(page.image.feature contains 'https') or (page.image.feature contains 'http')" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 7): Expected dotdot but found comparison in "(page.image.feature contains 'https') or (page.image.feature contains 'http')" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 7): Expected dotdot but found comparison in "(page.image.feature contains 'https') or (page.image.feature contains 'http')" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 7): Expected dotdot but found comparison in "(page.image.feature contains 'https') or (page.image.feature contains 'http')" in /_layouts/post.html
  Liquid Exception: Could not locate the included file 'icon-github.html' in any of ["/home/me/mysite/_includes", "/var/lib/gems/2.3.0/gems/leonids-0.1.1/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in about.md
jekyll 3.2.1 | Error:  Could not locate the included file 'icon-github.html' in any of ["/home/me/mysite/_includes", "/var/lib/gems/2.3.0/gems/leonids-0.1.1/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.

```

Am I missing something here?

Cheers 
kai*

**Comment by kmorgen1** [comment]
Okay, I figured that one out: You actually have to delete the content of the about.md shipped with the base jekyll install the liquid tags in there want to include that file that belongs to the default theme.

So now jekyll build does not throw an error but the site has no styles as - as far as I can tell - `css/font-awesome.min.css` is missing.

**Comment by renyuanz** [comment]
I didn't make any update to the Leonids gem so far, and it's currently unusable. But I can promise that gem version is coming alive in the next two months.

Thank you for your attention to this project.

**Comment by dmlicht** [comment]
Hey, I'm interested in using this gem and I've noticed the same issues.

**Comment by dluc** [comment]
thanks @kmorgen1 that works

**Comment by renyuanz** [comment]
I'm currently working on the ruby gem version. Almost done.

**Comment by renyuanz** [comment]
Got the gem works but I just figured out Github Pages only supports its official themes...so it may need a specific setup guide. Well, I just felt a little disappointed that Jekyll doesn't work the way simple which people have to do a lots of configurations.

I'm thinking to recreate the theme using Hexo or other static pages generator.
