### ISSUE TITLE
Eta for portfolio pages

### ISSUE THREAD

**Issue by KirillSuhodolov** [renyuanz/leonids#32]
Hi @renyuanz 
Your template looks amazing and pretty simple to start use. I spent few hours to choose from many others. 
Are you continue working on it and is it have sense to wait for updates(specially with portfolio pages)?

**Comment by renyuanz** [comment]
Hi @KirillSuhodolov 
I'm not working on it currently. But I think I'll still update this project if I have time, I can't make any promise but updates come maybe later this year.
