### ISSUE TITLE
Google Analytics not linked

### ISSUE THREAD

**Issue by joonan30** [renyuanz/leonids#38]
It seems `https` is missing from the js.html, for google analytics. 

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-XXXXXX-X', 'auto');
  ga('send', 'pageview');

</script>

https://github.com/renyuanz/leonids/blob/dfdd3fd5e159b3254be03293516c163f3f62e12e/_includes/js.html

**Comment by jaybkim1** [comment]
I don't think it is working in my page, too. 

Have you solved the problem, yet?

**Comment by renyuanz** [comment]
Issue [#56](https://github.com/renyuanz/leonids/issues/56) relevant
