### ISSUE TITLE
Extra slash on pages list

### ISSUE THREAD

**Issue by rnunesmagalhaes** [renyuanz/leonids#40]
On your personal site, the pages list has a trailing slash after "tags" ("home / ... / resume /  tags /"), and I'm having this issue on my site as well. I love your template design, but that extra slash is poking my OCD.

I see that on the leonids page, you don't have that trailing slash ("home / ... / categories /  tags"). I'd love to my page to look like that. Do you have any idea on how what is going on?

Thanks and congrats on the project.

**Comment by DracoBlue** [comment]
Should be fixed with #41
