### ISSUE TITLE
Resume section is missing

### ISSUE THREAD

**Issue by jaybkim1** [renyuanz/leonids#49]
Your template looks amazing and it is what I been looking for.

This is my first time opening my github blog, so this may sound silly to ask.

If i may, I see [Demo](http://renyuanz.github.io/leonids/) site has resume section on the left side of the page along with home/archive/categories/..., 

but [Mine](https://jaybkim1.github.io/) is missing.

Where do I need to take a look at?
 
Also, if you could guide me where I could change the text "A simple and awesome blog theme powered by jekyll.", I will be appreciated.

**Comment by renyuanz** [comment]
Adding a new Page is simple by creating a new html file in your jekyll project root directory, like so:

![screen shot 2017-08-14 at 13 45 53](https://user-images.githubusercontent.com/10615036/29270430-09fcf534-80f7-11e7-8138-f01bbd4a6197.png)

If you want a resume page, create a file called `resume.html` and make sure it has yaml front matter. You can simply copy my resume page content and modify it to whatever you want.

I think the text you'd like to change is at the footer section, if so, go to `leonids/_includes/footer.html` to change it.

Let me know if I helped you.

**Comment by jaybkim1** [comment]
Thank you for your quick reply!

I forked your project and expected to have same pages your DEMO has, but it seems like I am getting the **resume section(Image 2 below)** of the page.

What am i missing? Since i am not familiar with yaml front matter, i am learning it now.

![Image 1](https://user-images.githubusercontent.com/20435620/29302428-f4ace87e-81be-11e7-8594-e68749904ed2.png)

![Image 2](https://user-images.githubusercontent.com/20435620/29302429-f64fca02-81be-11e7-9648-e47ff55f0b93.png)

**Comment by renyuanz** [comment]
Resume page is using a `resume` layout which is added by the last commit [#47](https://github.com/renyuanz/leonids/pull/47).

So if you are Ok with the design, you can simply modify the content data from `leonids/_data/index/` directory where you got 4 yaml files.

If you want customize the page, you can either modify the `leonids/resume.html` file's layout to `layout: page` like this:

```
change this:
---
layout: resume
title: Resume
permalink: /resume/
---

to:

---
layout: page
title: Resume
permalink: /resume/
---
```
then add whatever html content you want,

or you can learn how we did it by loading data from `_data` directory and display them in `leonids/_layouts/resume.html`

**Comment by renyuanz** [comment]
I took a look at your repository, I think I probably find your problem.

If you named your repo like `yourname.github.io`, github will take `master` branch content to render a website. So you have to change `_config.yml` file in your master branch, but I won't suggest you to do that because the forked master branch is outdated.

What you can do is:

**make a new master branch with your gh-pages branch content, so nothing else you should modify to make it works.**

**Comment by jaybkim1** [comment]
Thank you for your well explanation! 

It really enlightened me what the issue was. 

"github takes `master branch` content to render a website if i named my repo like ` yourname.github.io`"

I should have taken a closer look at the [official docs](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) - this is for those of you who are struggling like me when publishing your blog using this amazing theme.

I got it working by changing my repo to ` yourname.github.io/blog`"

However, I am a bit curious about your first suggestion of making a new master branch with my gh-pages branch content.

**Do you mean I should delete the master branch and make gh-pages to be master?** 

It seems like right now in the settings, I cannot modify master branch to some other branches like below image.

![master](https://user-images.githubusercontent.com/20435620/29441186-61924f6e-8404-11e7-9613-472b373f04a8.PNG)

**Comment by renyuanz** [comment]
You can delete your master branch, that won't break things, and then recreate a new master branch from gh-pages.

**Comment by jaybkim1** [comment]
@renyuanz 

Thank you so much! I will close this issue.

**Comment by renyuanz** [comment]
You are welcome 😄
