### ISSUE TITLE
Aligning images inside the post

### ISSUE THREAD

**Issue by skywalker023** [renyuanz/leonids#50]
Hi, I've been using your theme for a while and I really appreciate your great work!

Mean while, it seems that your theme aligns the images inside the post to the left.
However, I'd like to fix that to center-align.
I tried fixing _global.scss and _normalize.scss by adding

margin-left: auto;
margin-right: auto;

to the "img" part.

But, it's not working..

Any suggestions?

Thanks

**Comment by renyuanz** [comment]
Actually, images are all responsive because I made them `max-width: 100%`, so typically they are "centered"

**Comment by skywalker023** [comment]
Typically they are centered, yes you're right.
However, the problem occurs when images have much longer height than width.
In this case, they are aligned to the left.

How can I fix this..?

**Comment by renyuanz** [comment]
I fixed this problem. The thing is if you want apply vertical align center to an element by margin auto, you should make it `display: block`. You can see what I did in the last commit [bf9f439](https://github.com/renyuanz/leonids/commit/bf9f4391357982bf7e38e85fe2131b4c73a28035).

**Comment by skywalker023** [comment]
Oh got it
Thank you!
