### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by jaybkim1** [renyuanz/leonids#56]
I notice there is below source codes for Google Analytics in js.html.
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', '{{ site.owner.google.analytics }}', 'auto');
  ga('send', 'pageview');
</script>
```
However, it does not seem to link to my google analytics.

All i did was to put my google analytics id starting with UA- in the _config.yml.

Is there something else I need to do?

**Comment by jaybkim1** [comment]
I believe [#38](https://github.com/renyuanz/leonids/issues/38) is the same issue, which was posted while back ago. But as it is still opened and is not answered by anyone, I would like to bring up this issue one more time.

**Comment by renyuanz** [comment]
I just pushed a commit [de0a79](https://github.com/renyuanz/leonids/commit/de0a79a76a2bd7e3d1be6288005a7c78a7aab113) that changed the protocol to explicit `https`.

I hope that will solve your problem as well.

**Comment by jaybkim1** [comment]
@renyuanz  
Thank you very much!
