### ISSUE TITLE
Github Pages Build Error - Config.yml

### ISSUE THREAD

**Issue by 7022Andre** [renyuanz/leonids#60]
GitHub is unable to build a Jekyll page when `_config.yml` is included in `.gitignore`. After I excluded/removed that line from `.gitignore` GitHub was able to build it. Maybe this info can be added to the readme file?

Thanks for creating a simple and nicely designed theme,
Andre

**Comment by renyuanz** [comment]
I didn't well document it. Thanks for point that out. I'm trying to find some free time to update it.
