### ISSUE TITLE
can i customize it?

### ISSUE THREAD

**Issue by skrish13** [renyuanz/leonids#61]
if i want to remove some `tabs` like lets say `resume` and add something custom, how would i go about it?

**Comment by renyuanz** [comment]
Remove `resume.html` in the root directory and add whatever you want and name it like `yourpage.html`

You can check [jekyll doc page](https://jekyllrb.com/docs/pages/) for more info.

**Comment by skrish13** [comment]
Yes, I realized that then itself, forgot to close the ticket. Thanks! :)
