### ISSUE TITLE
[Doubt] Is there a way to control the order of "pages" on the sidetab

### ISSUE THREAD

**Issue by skrish13** [renyuanz/leonids#66]
So if i add another "page", how can i change the order in which it appears here. See screenshot for reference.

![image](https://user-images.githubusercontent.com/10350518/31572302-c3c4dad8-b0c0-11e7-9ec4-f0f6c7e6519b.png)

**Comment by geeknerd** [comment]
You can modify the sidebar.html file in _includes folder. Where you have 
```
<li class="nav-item">
    <a href="{{ site.url }}/">home</a>
    <span>/</span>
</li>
```
You just manually add the other pages after it. e.g.
```
<li class="nav-item">
    <a href="{{ site.url }}/">home</a>
    <span>/</span>
</li>
<li class="nav-item">
    <a href="{{ site.url }}/resume">Resume</a>
    <span>/</span>
</li>
```
Not the most elegant way but it works.

**Comment by skrish13** [comment]
Hmm, okay. While we're here, let me ask this as well.

> 
> "Can I have a post or just a webpage, without it being one among [home/archive/categories/resume
> etc]  and not among the home page posts (this i already do by not
> posting in `_posts` directory).
> 
> You get my point right? Its not a "page" or a standard "post". Its just supposed
> to be a webpage (with 'post' layout but not part of the blog posts as such) (written in md ofc) which I can link to."

**Comment by geeknerd** [comment]
I see what you're trying to do. I know there is the drafts function but I'm not sure if that'll do the work. 
You could try adding a variable to posts and modify your index page like this:
[https://stackoverflow.com/a/31365506](url)

**Comment by skrish13** [comment]
Yaay, thanks for that link. removing just the `title` worked XP

**Comment by skrish13** [comment]
Hey @geeknerd, quick question, if I want to change my default homepage/landing page to something other than the actual "blog" page, how would i go about it? Thanks in advance :)

**Comment by renyuanz** [comment]
@skrish13 the content of the landing page is in `index.html`, you can just modify it.
