### ISSUE TITLE
OpenGraph title and description capture not working

### ISSUE THREAD

**Issue by mattouille** [renyuanz/leonids#68]
```
{% if page.title %}
  {% capture title %}{{ page.title }} | {{ site.title }}{% endcapture %}
{% else %}
  {% capture title %}{{ site.title }}{% endcapture %}
{% endif %}

{% if page.excerpt %}
  {% capture description %}{{ page.excerpt | strip_html | strip_newlines | truncate: 160 }}{% endcapture %}
{% else %}
  {% capture description %}{{ site.description }}{% endcapture %}
{% endif %}
```

**Comment by mattouille** [comment]
Actually, it looks to be picking it up but Facebook appears to be displaying the site title and description anyway.

**Comment by mattouille** [comment]
This actually makes more sense:
Invalid OG Type The provided 'og:type' of 'blog' is not valid

From: https://developers.facebook.com/tools/debug/sharing/

**Comment by mattouille** [comment]
Facebook was treating the site.url reference in og:url as a redirect and grabbing information from there.

Fix: `<meta property="og:url" content="{{ page.url | replace:'index.html','' | prepend: site.url }}">`

**Comment by renyuanz** [comment]
nice feedback!
