### ISSUE TITLE
Github Workflow vs. leonids Workflow

### ISSUE THREAD

**Issue by SLiNv** [renyuanz/leonids#82]
Hi @renyuanz , I'm just wonder what's the development workflow of this repo look like. It seems like master was the main development ```branch``` before and suddenly you started to work on ```gh-pages``` branch only without updating the ```master``` branch. 

There is a helpful gist showing how to keep ```gh-pages``` up to date with ```master```: [https://gist.github.com/mandiwise/44d1edce18f2ffb14f63](https://gist.github.com/mandiwise/44d1edce18f2ffb14f63)

As per [Github Workflow](https://guides.github.com/introduction/flow/), master branch should be the stable branch where changes or finished feature got merged in. A gh-pages is a a publishing source, in this repo's case, the gh-pages branch should reflect the new features/changes merged in to master branch. 

I'm just wanting to know the structure/organization of the repo so I can join the development and make pull request to the right branch :)

**Comment by renyuanz** [comment]
Hi @SLiNv, you are totally right, there aren't any "Leonids workflow", should have the master as the main branch and move out my perso info out to the gh-pages branch.

**Comment by SLiNv** [comment]
Thanks. Are you planning to organize the repo a little bit? I would love to contribute to the theme but I'm just a little bit confused where I should push PR to... and how you manage to sync between gh-page and master

**Comment by renyuanz** [comment]
Yes, I think if I have 30 minutes tonight I'll get it done.

I'll try something like post-commit hook to rebase gh-pages with master.
