### ISSUE TITLE
Adding custom Image to the sidebar

### ISSUE THREAD

**Issue by AntixK** [renyuanz/leonids#89]
I wish to add an image that spans the entire sidebar. How do I go about doing it?
I tried adding `background-image: url("back.png");` to the  _layout.scss file. (also tried giving the complete and relative urls to the image) but nothing happens.

Could you please help me?

**Comment by godixyz** [comment]
@AntixK update ?

**Comment by farhan-syah** [comment]
You need to  edit the css/main.scss or css/main.css file, with:

.table.cover {
backgound-image:url(your url here);
}
