### ISSUE TITLE
Error while converting site to HTTPS

### ISSUE THREAD

**Issue by an0th3rhuman** [renyuanz/leonids#91]
I changed my site to HTTPS.  But still the code is referring the asset with HTTP. Can someone point me where i can change it in the code base?

**Comment by renyuanz** [comment]
Hi,
Change `url` property in `_config.yml` file, check this line of code:
https://github.com/renyuanz/leonids/blob/0134f512b6afd27e564ba977b0f2bfb1209a4789/_config.yml#L9
