### ISSUE TITLE
Timeline to integrate custom css with GitHub Pages

### ISSUE THREAD

**Issue by Jas0nch** [renyuanz/leonids#93]
Hi, 

I noticed that the GitHub Pages used a specific path for custom CSS, any plans to support that by recreating a new file under the asset folder when building the site?

see [reference](https://help.github.com/en/enterprise/2.14/user/articles/customizing-css-and-html-in-your-jekyll-theme)

**Comment by renyuanz** [comment]
if this is related to the legacy Jekyll theme, unfortunately, it is not maintained anymore.
