### ISSUE TITLE
Tags Not Working

### ISSUE THREAD

**Issue by smsali97** [renyuanz/leonids#96]
Just got started with the template, and with the sample posts and all the tags aren't showing, any reason why this might be failing? Console log isnt showing any errors though. Attached screenshot below.

Edit: The Jekyll Drops was me trying to debug the `site.tags`

![image](https://user-images.githubusercontent.com/23452477/86432630-d8589880-bd11-11ea-9b62-ae85febafded.png)

**Comment by corriedotdev** [comment]
Hi. On your blog post in between the header meta data surrounded by --- have you included `tags: [mytag1, mytag2, etc]`

**Comment by smsali97** [comment]
yes I have! the tags metadata is already present in the sample posts.

*Best,*

*Syed Mohammad Sualeh Ali*

**Comment by smsali97** [comment]
Resolved, was a typo . sorry for the trouble :)
