### ISSUE TITLE
Why did you decide to change?

### ISSUE THREAD

**Issue by horotat** [renyuanz/leonids#97]
Hello,
I am just curious to know. I made [my current site](https://ali.mk) based on your previous Jekyll theme. Why did you decide to change from Jekyll to Gatsby?

**Comment by renyuanz** [comment]
Hi @horotat !
It was a [promise](https://github.com/renyuanz/leonids/issues/80) I made 2 years ago, Gatsby got more votes against VuePress or other options. And I recently got some experiences to rebuild a legacy project at work using Gatsby, it is easier for me with this stack.
And I got some free spare time and I want to try out how to make a dark mode for a site, so I made it. 😺

**Comment by horotat** [comment]
Cool, but I wanted to know what do you personally think are the advantages of Gatsby over Jekyll?

I've seen it's much faster! But I'm really bad at choosing stuff 😀

I guess as a personal website Jekyll should be more suitable for me, no?

**Comment by renyuanz** [comment]
It's much faster, and to be honest, but having a steep learning curve as well.
It writes on React.js and GraphQL, which means JSX, react life cycles, react SSR, and GraphQL usage.
All performance improvements come with a cost, and in this case, a high cost for beginners who just want to write a blog post.
But it is also fun to learn new things, to understand why people tend to use these technologies.

It's about the trade-offs. If you want to fast prototype something and get it online, uses whatever you feel comfortable and productive with. If you want to learn something new, pick something that will add more values for yourself, your career.

Yes, for a personal website, and you need to easily customize your site with simplest CSS and JS tag, go ahead with Jekyll, it's always a good choice.

**Comment by horotat** [comment]
Yeah, thank you. I have seen that Gatsby is crazily fast. For now I want to have my website up. But then when I get some time I will go through these new technologies to learn and not get outdated 😄. The sad fact however, is that I just learned Jekyll and already it is getting outdated 😆.

Good Luck.
